export default {
    survey: {
        canBeExported: true,
        languages: ['ar-SA', 'en-US'],
        trial: false,
        hasNPSQuestion: false,
        hasRatingQuestion: true,
        hasCESQuestion: false,
        hasCSATQuestion: true,
        hasQuotas: false,
        hasQuestions: true,
        id: 'O9dS6FIacFilIPje6bAa',
        defaultLanguage: 'ar-SA',
        surveyFolderId: '4FCBAC8715C049A1907FA3171F3C4247',
        progressDisplayModeId: 4,
        resumeModeID: 1,
        changeModeID: 1,
        privacyActionID: 1,
        creationDate: '2024-10-20T13:23:53.257Z',
        title: 'content evaluation',
        surveyDisplayTimes: 0,
        resultsDisplayTimes: 0,
        archive: false,
        activated: false,
        scored: false,
        iPExpires: 1440,
        cookieExpires: 1440,
        onlyInvited: false,
        unAuthentifiedUserActionID: 1,
        questionNumberingDisabled: true,
        multiLanguageModeId: 1,
        anonymousRespondents: false,
        showAnswerSummary: false,
        buttonRowDisplayId: 1,
        allowAnswerDownload: false,
        surveyStatusId: 1,
        redirectionDelay: 0,
        forceHttps: false,
        surveyLanguageCode: 'ar-SA',
        formStyleId: 'Mz5HiBsMY7bLES03XQwa',
        highlightRespondentAnswers: false,
        buttonDisplayMode: 31,
        pageNavigatorTypeId: 1,
        clearSkippedPages: true,
        validatePageOnChange: true,
        disableUnvisitedPages: false,
        ignoreInvalidPagesOnSubmit: false,
        alwaysDisplaySubmitButton: false,
        confirmExit: true,
        versioningTypeId: 1,
        mobileQuestionPageRenderingID: 3,
        keepLayoutOnMobileDevices: false,
        enableServerSideValidation: true,
        storeRespondentGeolocation: false,
        securityDataClass: 0,
        disableFlowActions: false,
        conversational: false,
        wipeItemsOlderThanDays: 2,
        enableGDPR: false,
        enableGDPRRightToForget: false,
        enableCookieConsent: false,
        allowGoogleAnalyticsDisabling: false,
        allowRespondentToDeleteAnswers: false,
        allowRespondentToDownloadAnswers: false,
        iPGeolocation: false,
        offlineEnabled: false,
        offlineRespondentManager: false,
        offlineAutoUpload: false,
        offlineRestartSessionButton: false,
        questionsFlowTarget: 0,
    },
    pages: [
        {
            id: 'F8570195B11A499799FE3CE393C0B955',
            pageNumber: 1,
            surveyId: 'O9dS6FIacFilIPje6bAa',
            type: '9EF2F6A5-21DF-4E07-8182-E6E108EEB366',
            randomizeQuestions: false,
            enableSubmitButton: false,
            displayQuestionNumber: false,
            useDefaultHeaderFooter: true,
            disableResponseTimer: false,
            disabled: false,
            displayAllQuestions: false,
            highlightRespondentReportAnswers: false,
            useDefaultPageNavigator: true,
            deadEnd: false,
        },
    ],
    questions: [
        {
            questionVersionUId: '92ad2097-3d25-47c8-848a-00615680c2ff',
            repeatableSectionModeId: 0,
            maxSections: 0,
            typeMode: 7,
            typeCSS: 'ngs-question-csat-image',
            isPanelCreator: false,
            questionChildCount: 0,
            excludedFromLink: false,
            pageId: 'F8570195B11A499799FE3CE393C0B955',
            displayOrder: 1,
            disabled: false,
            surveyId: 'O9dS6FIacFilIPje6bAa',
            id: 'O9dS8wLNWmhOa4ox0RYa',
            layoutModeId: 2,
            selectionModeId: 18,
            columnsNumber: 0,
            text: '<p>هل المحتوى مفيد؟</p>\n',
            minSelectionRequired: 1,
            maxSelectionAllowed: 0,
            ratingEnabled: true,
            randomizeAnswers: false,
            isExtendedFilter: false,
            hideValidationAsterix: true,
            calculationModeId: 1,
            displayQuestionHeader: true,
            rotateMatrix: false,
            blockQuestionColumnsNumber: 0,
            newPanelistAllowed: false,
            editableAnswers: false,
            selectionsAsButton: false,
            defaultReport: false,
            childQuestionsRandomize: false,
            conversationReplyType: 0,
            answerSortOrder: 0,
            requiredValidationType: 0,
            linkedQuestionPipeType: 0,
            linkedQuestionPipeTarget: 0,
            deleted: false,
        },
        {
            questionVersionUId: '0f01e176-bf47-40c2-b0b7-acb0b71a3ac8',
            repeatableSectionModeId: 0,
            maxSections: 0,
            typeMode: 30759,
            typeCSS: 'ngs-question-hidden',
            isPanelCreator: false,
            questionChildCount: 0,
            excludedFromLink: false,
            pageId: 'F8570195B11A499799FE3CE393C0B955',
            displayOrder: 2,
            disabled: false,
            surveyId: 'O9dS6FIacFilIPje6bAa',
            id: 'OBPhaYxAXssimeva1X7a',
            layoutModeId: 1,
            selectionModeId: 7,
            columnsNumber: 0,
            text: '<p>version</p>\n',
            minSelectionRequired: 0,
            maxSelectionAllowed: 0,
            ratingEnabled: false,
            randomizeAnswers: false,
            isExtendedFilter: false,
            hideValidationAsterix: true,
            calculationModeId: 1,
            displayQuestionHeader: true,
            rotateMatrix: false,
            blockQuestionColumnsNumber: 0,
            newPanelistAllowed: false,
            editableAnswers: true,
            selectionsAsButton: false,
            defaultReport: false,
            childQuestionsRandomize: false,
            conversationReplyType: 0,
            answerSortOrder: 0,
            requiredValidationType: 0,
            linkedQuestionPipeType: 0,
            linkedQuestionPipeTarget: 0,
            deleted: false,
        },
        {
            questionVersionUId: '471fa9e1-a7dc-410f-812c-b230adc1e7a7',
            repeatableSectionModeId: 0,
            maxSections: 0,
            typeMode: 30759,
            typeCSS: 'ngs-question-hidden',
            isPanelCreator: false,
            questionChildCount: 0,
            excludedFromLink: false,
            pageId: 'F8570195B11A499799FE3CE393C0B955',
            displayOrder: 3,
            disabled: false,
            surveyId: 'O9dS6FIacFilIPje6bAa',
            id: 'OBPhpQGM9Lef1Blo86da',
            layoutModeId: 1,
            selectionModeId: 7,
            columnsNumber: 0,
            text: '<p>environment</p>\n',
            minSelectionRequired: 0,
            maxSelectionAllowed: 0,
            ratingEnabled: false,
            randomizeAnswers: false,
            isExtendedFilter: false,
            hideValidationAsterix: true,
            calculationModeId: 1,
            displayQuestionHeader: true,
            rotateMatrix: false,
            blockQuestionLayoutId: 1,
            blockQuestionColumnsNumber: 0,
            newPanelistAllowed: false,
            editableAnswers: true,
            selectionsAsButton: false,
            defaultReport: false,
            childQuestionsRandomize: false,
            conversationReplyType: 0,
            answerSortOrder: 0,
            requiredValidationType: 0,
            linkedQuestionPipeType: 0,
            linkedQuestionPipeTarget: 0,
            deleted: false,
        },
        {
            questionVersionUId: 'a2eed3a8-5a47-4987-8736-386c253f799d',
            repeatableSectionModeId: 0,
            maxSections: 0,
            typeMode: 30759,
            typeCSS: 'ngs-question-hidden',
            isPanelCreator: false,
            questionChildCount: 0,
            excludedFromLink: false,
            pageId: 'F8570195B11A499799FE3CE393C0B955',
            displayOrder: 4,
            disabled: false,
            surveyId: 'O9dS6FIacFilIPje6bAa',
            id: 'OBeQRV5RV47s0JiPzJxa',
            layoutModeId: 1,
            selectionModeId: 7,
            columnsNumber: 0,
            text: '<p>alias</p>\n',
            minSelectionRequired: 0,
            maxSelectionAllowed: 0,
            ratingEnabled: false,
            randomizeAnswers: false,
            isExtendedFilter: false,
            hideValidationAsterix: true,
            calculationModeId: 1,
            displayQuestionHeader: true,
            rotateMatrix: false,
            blockQuestionColumnsNumber: 0,
            newPanelistAllowed: false,
            editableAnswers: true,
            selectionsAsButton: false,
            defaultReport: false,
            childQuestionsRandomize: false,
            conversationReplyType: 0,
            answerSortOrder: 0,
            requiredValidationType: 0,
            linkedQuestionPipeType: 0,
            linkedQuestionPipeTarget: 0,
            deleted: false,
        },
        {
            questionVersionUId: 'd7a7e618-40de-4e6e-bfb2-653005d3d7d7',
            repeatableSectionModeId: 0,
            maxSections: 0,
            typeMode: 30743,
            typeCSS: 'ngs-question-multi',
            isPanelCreator: false,
            questionChildCount: 0,
            excludedFromLink: false,
            pageId: 'F8570195B11A499799FE3CE393C0B955',
            displayOrder: 5,
            disabled: false,
            surveyId: 'O9dS6FIacFilIPje6bAa',
            id: 'OFRZZx9ds475lN5SOSaa',
            layoutModeId: 1,
            selectionModeId: 2,
            columnsNumber: 0,
            text: '<p>أسباب تقييمك</p>\n',
            minSelectionRequired: 1,
            maxSelectionAllowed: 0,
            ratingEnabled: false,
            randomizeAnswers: false,
            isExtendedFilter: false,
            hideValidationAsterix: true,
            calculationModeId: 1,
            displayQuestionHeader: true,
            rotateMatrix: false,
            blockQuestionColumnsNumber: 0,
            newPanelistAllowed: false,
            editableAnswers: true,
            selectionsAsButton: false,
            defaultReport: false,
            childQuestionsRandomize: false,
            conversationReplyType: 0,
            answerSortOrder: 0,
            requiredValidationType: 0,
            linkedQuestionPipeType: 0,
            linkedQuestionPipeTarget: 0,
            deleted: false,
        },
        {
            questionVersionUId: '096a92a1-6898-492c-aa8f-a3a9b3bbca80',
            repeatableSectionModeId: 0,
            maxSections: 0,
            typeMode: 30727,
            typeCSS: 'ngs-question-single',
            isPanelCreator: false,
            questionChildCount: 0,
            excludedFromLink: false,
            pageId: 'F8570195B11A499799FE3CE393C0B955',
            displayOrder: 6,
            disabled: false,
            surveyId: 'O9dS6FIacFilIPje6bAa',
            id: 'OFRZ_djnb7Autansgo0a',
            layoutModeId: 1,
            selectionModeId: 1,
            columnsNumber: 0,
            text: '<p>ملاحظات أخرى</p>\n',
            minSelectionRequired: 0,
            maxSelectionAllowed: 0,
            ratingEnabled: false,
            randomizeAnswers: false,
            isExtendedFilter: false,
            hideValidationAsterix: true,
            calculationModeId: 1,
            displayQuestionHeader: true,
            rotateMatrix: false,
            blockQuestionColumnsNumber: 0,
            newPanelistAllowed: false,
            editableAnswers: true,
            selectionsAsButton: false,
            defaultReport: false,
            childQuestionsRandomize: false,
            conversationReplyType: 0,
            answerSortOrder: 0,
            requiredValidationType: 0,
            linkedQuestionPipeType: 0,
            linkedQuestionPipeTarget: 0,
            deleted: false,
        },
        {
            questionVersionUId: '5d63f724-3029-4c85-a3ab-748be78a08d2',
            repeatableSectionModeId: 0,
            maxSections: 0,
            typeMode: 30743,
            typeCSS: 'ngs-question-multi',
            isPanelCreator: false,
            questionChildCount: 0,
            excludedFromLink: false,
            pageId: 'F8570195B11A499799FE3CE393C0B955',
            displayOrder: 7,
            disabled: false,
            surveyId: 'O9dS6FIacFilIPje6bAa',
            id: 'OFRaw38jb6_z40sHAM_a',
            layoutModeId: 1,
            selectionModeId: 2,
            columnsNumber: 0,
            text: '<p>أسباب تقييمك</p>\n',
            minSelectionRequired: 1,
            maxSelectionAllowed: 0,
            ratingEnabled: false,
            randomizeAnswers: false,
            isExtendedFilter: false,
            hideValidationAsterix: true,
            calculationModeId: 1,
            displayQuestionHeader: true,
            rotateMatrix: false,
            blockQuestionColumnsNumber: 0,
            newPanelistAllowed: false,
            editableAnswers: true,
            selectionsAsButton: false,
            defaultReport: false,
            childQuestionsRandomize: false,
            conversationReplyType: 0,
            answerSortOrder: 0,
            requiredValidationType: 0,
            linkedQuestionPipeType: 0,
            linkedQuestionPipeTarget: 0,
            deleted: false,
        },
        {
            questionVersionUId: '7ea0ec6a-be61-4c91-95f5-0e99cde001fc',
            repeatableSectionModeId: 0,
            maxSections: 0,
            typeMode: 30727,
            typeCSS: 'ngs-question-single',
            isPanelCreator: false,
            questionChildCount: 0,
            excludedFromLink: false,
            pageId: 'F8570195B11A499799FE3CE393C0B955',
            displayOrder: 8,
            disabled: false,
            surveyId: 'O9dS6FIacFilIPje6bAa',
            id: 'OFRbewX_Dd4Dt9xTip_a',
            layoutModeId: 1,
            selectionModeId: 1,
            columnsNumber: 0,
            text: '<p>ملاحظات أخرى</p>\n',
            minSelectionRequired: 0,
            maxSelectionAllowed: 0,
            ratingEnabled: false,
            randomizeAnswers: false,
            isExtendedFilter: false,
            hideValidationAsterix: true,
            calculationModeId: 1,
            displayQuestionHeader: true,
            rotateMatrix: false,
            blockQuestionColumnsNumber: 0,
            newPanelistAllowed: false,
            editableAnswers: true,
            selectionsAsButton: false,
            defaultReport: false,
            childQuestionsRandomize: false,
            conversationReplyType: 0,
            answerSortOrder: 0,
            requiredValidationType: 0,
            linkedQuestionPipeType: 0,
            linkedQuestionPipeTarget: 0,
            deleted: false,
        },
        {
            questionVersionUId: '621d9f0c-1637-4f11-b828-7a7cfff2e344',
            repeatableSectionModeId: 0,
            maxSections: 0,
            typeMode: 30727,
            typeCSS: 'ngs-question-single',
            isPanelCreator: false,
            questionChildCount: 0,
            excludedFromLink: false,
            pageId: 'F8570195B11A499799FE3CE393C0B955',
            displayOrder: 9,
            disabled: false,
            surveyId: 'O9dS6FIacFilIPje6bAa',
            id: 'OLcm__sfNaCP2yQ_gG0a',
            layoutModeId: 1,
            selectionModeId: 1,
            columnsNumber: 0,
            text: '<p>الجنس</p>\n',
            minSelectionRequired: 1,
            maxSelectionAllowed: 0,
            ratingEnabled: false,
            randomizeAnswers: false,
            isExtendedFilter: false,
            hideValidationAsterix: true,
            calculationModeId: 1,
            displayQuestionHeader: true,
            rotateMatrix: false,
            blockQuestionColumnsNumber: 0,
            newPanelistAllowed: false,
            editableAnswers: true,
            selectionsAsButton: false,
            defaultReport: false,
            childQuestionsRandomize: false,
            conversationReplyType: 1,
            answerSortOrder: 0,
            requiredValidationType: 0,
            linkedQuestionPipeType: 0,
            linkedQuestionPipeTarget: 0,
            deleted: false,
        },
    ],
    answers: [
        {
            typeMode: 1,
            itemCollectionMultipleSelection: false,
            id: '195F3674A8D440E7B49EA8A76D4FDBDF',
            questionId: 'OFRaw38jb6_z40sHAM_a',
            answerTypeId: '3A77D792-008A-463B-926F-663C9C115938',
            typeId: 'AnswerSelectionItem',
            text: 'المحتوى غير متسق',
            displayOrder: 3,
            required: false,
            fixedDisplayOrder: false,
            answerDisplayBehaviorId: 1,
            syncRefMandatory: false,
            answerFormId: 'B9EFA89B-811C-4982-B909-87C16E063CDA',
            uniqueAnswer: false,
            fixedDisplayBehavior: false,
            computeSentimentScore: false,
            extractKeyPhrases: false,
            readOnly: false,
            dataClass: 0,
            charCounter: false,
            wordCounter: false,
            deleted: false,
            requiredValidationType: 0,
            enableSearchFilter: false,
            enableSelectAll: false,
            excludeFromLink: false,
            hideUntilSelected: false,
        },
        {
            typeMode: 1,
            itemCollectionMultipleSelection: false,
            id: '27ACB083CAD349D4B93505DFB35630AF',
            questionId: 'OFRaw38jb6_z40sHAM_a',
            answerTypeId: '3A77D792-008A-463B-926F-663C9C115938',
            typeId: 'AnswerSelectionItem',
            text: 'صعوبة الوصول',
            displayOrder: 1,
            selected: false,
            scorePoint: 0,
            required: false,
            fixedDisplayOrder: false,
            answerDisplayBehaviorId: 1,
            syncRefMandatory: false,
            answerFormId: '559754C9-4FF4-4696-8155-523766115419',
            uniqueAnswer: false,
            fixedDisplayBehavior: false,
            computeSentimentScore: false,
            extractKeyPhrases: false,
            readOnly: false,
            dataClass: 0,
            charCounter: false,
            wordCounter: false,
            deleted: false,
            requiredValidationType: 0,
            enableSearchFilter: false,
            enableSelectAll: false,
            excludeFromLink: false,
            hideUntilSelected: false,
        },
        {
            typeMode: 1,
            itemCollectionMultipleSelection: false,
            id: '66E6156705C548E283AE820C99027FAF',
            questionId: 'OFRZZx9ds475lN5SOSaa',
            answerTypeId: '3A77D792-008A-463B-926F-663C9C115938',
            typeId: 'AnswerSelectionItem',
            text: 'دقة المعلومات',
            displayOrder: 2,
            required: false,
            fixedDisplayOrder: false,
            answerDisplayBehaviorId: 1,
            syncRefMandatory: false,
            answerFormId: 'AD8509AB-FE84-4A53-9AB4-C6CCC02EFF6E',
            uniqueAnswer: false,
            fixedDisplayBehavior: false,
            computeSentimentScore: false,
            extractKeyPhrases: false,
            readOnly: false,
            dataClass: 0,
            charCounter: false,
            wordCounter: false,
            deleted: false,
            requiredValidationType: 0,
            enableSearchFilter: false,
            enableSelectAll: false,
            excludeFromLink: false,
            hideUntilSelected: false,
        },
        {
            typeMode: 1,
            itemCollectionMultipleSelection: false,
            id: '6C34CDBE7B0A4CD0887C8EC8974CB96D',
            questionId: 'OFRZZx9ds475lN5SOSaa',
            answerTypeId: '3A77D792-008A-463B-926F-663C9C115938',
            typeId: 'AnswerSelectionItem',
            text: 'اتساق المحتوى',
            displayOrder: 3,
            required: false,
            fixedDisplayOrder: false,
            answerDisplayBehaviorId: 1,
            syncRefMandatory: false,
            answerFormId: 'B9EFA89B-811C-4982-B909-87C16E063CDA',
            uniqueAnswer: false,
            fixedDisplayBehavior: false,
            computeSentimentScore: false,
            extractKeyPhrases: false,
            readOnly: false,
            dataClass: 0,
            charCounter: false,
            wordCounter: false,
            deleted: false,
            requiredValidationType: 0,
            enableSearchFilter: false,
            enableSelectAll: false,
            excludeFromLink: false,
            hideUntilSelected: false,
        },
        {
            typeMode: 1,
            itemCollectionMultipleSelection: false,
            id: '82D4349CBCB94CAF83E0F249D5664DE3',
            questionId: 'OFRZZx9ds475lN5SOSaa',
            answerTypeId: '3A77D792-008A-463B-926F-663C9C115938',
            typeId: 'AnswerSelectionItem',
            text: 'سبب آخر',
            displayOrder: 4,
            required: false,
            fixedDisplayOrder: false,
            answerDisplayBehaviorId: 1,
            syncRefMandatory: false,
            answerFormId: '3654EABD-D76F-4598-B694-2E42A648AA49',
            uniqueAnswer: false,
            fixedDisplayBehavior: false,
            computeSentimentScore: false,
            extractKeyPhrases: false,
            readOnly: false,
            dataClass: 0,
            charCounter: false,
            wordCounter: false,
            deleted: false,
            requiredValidationType: 0,
            enableSearchFilter: false,
            enableSelectAll: false,
            excludeFromLink: false,
            hideUntilSelected: false,
        },
        {
            typeMode: 141522,
            itemCollectionMultipleSelection: false,
            id: '85C2F2282A194CD5858833EEA477AF16',
            questionId: 'OFRbewX_Dd4Dt9xTip_a',
            answerTypeId: '7A06967B-8BC7-4F9A-826C-206DE9DF5320',
            typeId: 'AnswerFieldItem',
            displayOrder: 1,
            selected: false,
            scorePoint: 0,
            required: false,
            fixedDisplayOrder: false,
            answerDisplayBehaviorId: 1,
            syncRefMandatory: false,
            answerFormId: '23620C5D-4C46-4C86-93B5-26F65BD46E3F',
            uniqueAnswer: false,
            fixedDisplayBehavior: false,
            computeSentimentScore: false,
            extractKeyPhrases: false,
            readOnly: false,
            dataClass: 0,
            charCounter: false,
            wordCounter: false,
            deleted: false,
            requiredValidationType: 0,
            enableSearchFilter: false,
            enableSelectAll: false,
            excludeFromLink: false,
            hideUntilSelected: false,
        },
        {
            typeMode: 141522,
            itemCollectionMultipleSelection: false,
            id: 'AD08269D1AB1417E90CDAB47CDF84EA6',
            questionId: 'OFRZ_djnb7Autansgo0a',
            answerTypeId: '7A06967B-8BC7-4F9A-826C-206DE9DF5320',
            typeId: 'AnswerFieldItem',
            displayOrder: 1,
            selected: false,
            scorePoint: 0,
            required: false,
            fixedDisplayOrder: false,
            answerDisplayBehaviorId: 1,
            syncRefMandatory: false,
            answerFormId: '23620C5D-4C46-4C86-93B5-26F65BD46E3F',
            uniqueAnswer: false,
            fixedDisplayBehavior: false,
            computeSentimentScore: false,
            extractKeyPhrases: false,
            readOnly: false,
            dataClass: 0,
            charCounter: false,
            wordCounter: false,
            deleted: false,
            requiredValidationType: 0,
            enableSearchFilter: false,
            enableSelectAll: false,
            excludeFromLink: false,
            hideUntilSelected: false,
        },
        {
            typeMode: 1,
            itemCollectionMultipleSelection: false,
            id: 'C5AEB165F3564264ABD94159CE5530C4',
            questionId: 'OFRZZx9ds475lN5SOSaa',
            answerTypeId: '3A77D792-008A-463B-926F-663C9C115938',
            typeId: 'AnswerSelectionItem',
            text: 'سهولة الوصول',
            displayOrder: 1,
            selected: false,
            scorePoint: 0,
            required: false,
            fixedDisplayOrder: false,
            answerDisplayBehaviorId: 1,
            syncRefMandatory: false,
            answerFormId: '559754C9-4FF4-4696-8155-523766115419',
            uniqueAnswer: false,
            fixedDisplayBehavior: false,
            computeSentimentScore: false,
            extractKeyPhrases: false,
            readOnly: false,
            dataClass: 0,
            charCounter: false,
            wordCounter: false,
            deleted: false,
            requiredValidationType: 0,
            enableSearchFilter: false,
            enableSelectAll: false,
            excludeFromLink: false,
            hideUntilSelected: false,
        },
        {
            typeMode: 1,
            itemCollectionMultipleSelection: false,
            id: 'E59B0572787C4C32836355C53B1B6A38',
            questionId: 'OFRaw38jb6_z40sHAM_a',
            answerTypeId: '3A77D792-008A-463B-926F-663C9C115938',
            typeId: 'AnswerSelectionItem',
            text: 'المعلومات غير دقيقة',
            displayOrder: 2,
            required: false,
            fixedDisplayOrder: false,
            answerDisplayBehaviorId: 1,
            syncRefMandatory: false,
            answerFormId: 'AD8509AB-FE84-4A53-9AB4-C6CCC02EFF6E',
            uniqueAnswer: false,
            fixedDisplayBehavior: false,
            computeSentimentScore: false,
            extractKeyPhrases: false,
            readOnly: false,
            dataClass: 0,
            charCounter: false,
            wordCounter: false,
            deleted: false,
            requiredValidationType: 0,
            enableSearchFilter: false,
            enableSelectAll: false,
            excludeFromLink: false,
            hideUntilSelected: false,
        },
        {
            typeMode: 1,
            itemCollectionMultipleSelection: false,
            id: 'EBA70008C64B4E2EB04476C0EF65D61B',
            questionId: 'OFRaw38jb6_z40sHAM_a',
            answerTypeId: '3A77D792-008A-463B-926F-663C9C115938',
            typeId: 'AnswerSelectionItem',
            text: 'سبب آخر',
            displayOrder: 4,
            required: false,
            fixedDisplayOrder: false,
            answerDisplayBehaviorId: 1,
            syncRefMandatory: false,
            answerFormId: '3654EABD-D76F-4598-B694-2E42A648AA49',
            uniqueAnswer: false,
            fixedDisplayBehavior: false,
            computeSentimentScore: false,
            extractKeyPhrases: false,
            readOnly: false,
            dataClass: 0,
            charCounter: false,
            wordCounter: false,
            deleted: false,
            requiredValidationType: 0,
            enableSearchFilter: false,
            enableSelectAll: false,
            excludeFromLink: false,
            hideUntilSelected: false,
        },
        {
            typeMode: 1,
            itemCollectionMultipleSelection: false,
            id: 'O9dS8wLNWmhOa4ox0R_a',
            questionId: 'O9dS8wLNWmhOa4ox0RYa',
            answerTypeId: '3A77D792-008A-463B-926F-663C9C115938',
            typeId: 'AnswerSelectionItem',
            text: '1',
            imageURL: '/assets/images/forms/thumbsdown.png',
            displayOrder: 2,
            required: false,
            reportingAlias: '1',
            ratingWeight: 1,
            answerFormId: '4832D587-E429-413D-91F8-9150A9124F30',
            uniqueAnswer: false,
            computeSentimentScore: false,
            extractKeyPhrases: false,
            readOnly: false,
            dataClass: 0,
            charCounter: false,
            wordCounter: false,
            deleted: false,
            requiredValidationType: 0,
            enableSearchFilter: false,
            enableSelectAll: false,
            excludeFromLink: false,
            hideUntilSelected: false,
        },
        {
            typeMode: 1,
            itemCollectionMultipleSelection: false,
            id: 'O9dS8wLNWmhOa4ox0RZa',
            questionId: 'O9dS8wLNWmhOa4ox0RYa',
            answerTypeId: '3A77D792-008A-463B-926F-663C9C115938',
            typeId: 'AnswerSelectionItem',
            text: '10',
            imageURL: '/assets/images/forms/thumbsup.png',
            displayOrder: 1,
            required: false,
            reportingAlias: '10',
            ratingWeight: 5,
            answerFormId: '6074A0FD-41B0-40E4-B678-521502F806AD',
            uniqueAnswer: false,
            computeSentimentScore: false,
            extractKeyPhrases: false,
            readOnly: false,
            dataClass: 0,
            charCounter: false,
            wordCounter: false,
            deleted: false,
            requiredValidationType: 0,
            enableSearchFilter: false,
            enableSelectAll: false,
            excludeFromLink: false,
            hideUntilSelected: false,
        },
        {
            typeMode: 141522,
            itemCollectionMultipleSelection: false,
            id: 'OBeQRV5RV47s0JiPzJya',
            questionId: 'OBeQRV5RV47s0JiPzJxa',
            answerTypeId: 'D54B1F97-E260-4E7C-92AB-3245F8194175',
            typeId: 'AnswerFieldItem',
            displayOrder: 1,
            selected: false,
            scorePoint: 0,
            required: false,
            fixedDisplayOrder: false,
            answerDisplayBehaviorId: 1,
            answerFormId: 'FDD7AA22-B804-45D1-A4D1-86A3ADF693CD',
            uniqueAnswer: false,
            fixedDisplayBehavior: false,
            computeSentimentScore: false,
            extractKeyPhrases: false,
            readOnly: false,
            dataClass: 0,
            charCounter: false,
            wordCounter: false,
            deleted: false,
            requiredValidationType: 0,
            enableSearchFilter: false,
            enableSelectAll: false,
            excludeFromLink: false,
            hideUntilSelected: false,
        },
        {
            typeMode: 141522,
            itemCollectionMultipleSelection: false,
            id: 'OBPhaYxAXssimeva1X8a',
            questionId: 'OBPhaYxAXssimeva1X7a',
            answerTypeId: 'D54B1F97-E260-4E7C-92AB-3245F8194175',
            typeId: 'AnswerFieldItem',
            displayOrder: 1,
            selected: false,
            scorePoint: 0,
            required: false,
            fixedDisplayOrder: false,
            answerDisplayBehaviorId: 1,
            answerFormId: '9B40E468-F103-48F4-80DE-B418AB7040C4',
            uniqueAnswer: false,
            fixedDisplayBehavior: false,
            computeSentimentScore: false,
            extractKeyPhrases: false,
            readOnly: false,
            dataClass: 0,
            charCounter: false,
            wordCounter: false,
            deleted: false,
            requiredValidationType: 0,
            enableSearchFilter: false,
            enableSelectAll: false,
            excludeFromLink: false,
            hideUntilSelected: false,
        },
        {
            typeMode: 141522,
            itemCollectionMultipleSelection: false,
            id: 'OBPhpQGM9Lef1Blo86ea',
            questionId: 'OBPhpQGM9Lef1Blo86da',
            answerTypeId: 'D54B1F97-E260-4E7C-92AB-3245F8194175',
            typeId: 'AnswerFieldItem',
            displayOrder: 1,
            selected: false,
            scorePoint: 0,
            required: false,
            fixedDisplayOrder: false,
            answerDisplayBehaviorId: 1,
            answerFormId: '36585B1C-D3FB-4083-989D-BD46637627E8',
            uniqueAnswer: false,
            fixedDisplayBehavior: false,
            computeSentimentScore: false,
            extractKeyPhrases: false,
            readOnly: false,
            dataClass: 0,
            charCounter: false,
            wordCounter: false,
            deleted: false,
            requiredValidationType: 0,
            enableSearchFilter: false,
            enableSelectAll: false,
            excludeFromLink: false,
            hideUntilSelected: false,
        },
        {
            typeMode: 1,
            itemCollectionMultipleSelection: false,
            id: 'OLcm__sfNaCP2yQ_gG1a',
            questionId: 'OLcm__sfNaCP2yQ_gG0a',
            answerTypeId: '3A77D792-008A-463B-926F-663C9C115938',
            typeId: 'AnswerSelectionItem',
            text: 'أفضل عدم الإفصاح',
            displayOrder: 3,
            selected: false,
            scorePoint: 0,
            required: false,
            fixedDisplayOrder: false,
            answerDisplayBehaviorId: 1,
            answerFormId: 'EA75A997-D420-4238-8189-BD41F20B945F',
            uniqueAnswer: false,
            fixedDisplayBehavior: false,
            computeSentimentScore: false,
            extractKeyPhrases: false,
            readOnly: false,
            dataClass: 0,
            charCounter: false,
            wordCounter: false,
            deleted: false,
            requiredValidationType: 0,
            enableSearchFilter: false,
            enableSelectAll: false,
            excludeFromLink: false,
            hideUntilSelected: false,
        },
        {
            typeMode: 1,
            itemCollectionMultipleSelection: false,
            id: 'OLcmgXANqae1twOtXhGa',
            questionId: 'OLcm__sfNaCP2yQ_gG0a',
            answerTypeId: '3A77D792-008A-463B-926F-663C9C115938',
            typeId: 'AnswerSelectionItem',
            text: 'ذكر',
            displayOrder: 1,
            required: false,
            answerFormId: 'AA245574-3840-45C7-871E-D6601D412FBC',
            uniqueAnswer: false,
            computeSentimentScore: false,
            extractKeyPhrases: false,
            readOnly: false,
            dataClass: 0,
            charCounter: false,
            wordCounter: false,
            deleted: false,
            requiredValidationType: 0,
            enableSearchFilter: false,
            enableSelectAll: false,
            excludeFromLink: false,
            hideUntilSelected: false,
        },
        {
            typeMode: 1,
            itemCollectionMultipleSelection: false,
            id: 'OLcmhmcC1Vnq0V3ozwza',
            questionId: 'OLcm__sfNaCP2yQ_gG0a',
            answerTypeId: '3A77D792-008A-463B-926F-663C9C115938',
            typeId: 'AnswerSelectionItem',
            text: 'أنثى',
            displayOrder: 2,
            required: false,
            answerFormId: 'BBE64DA7-FFC8-4688-A59C-0A02D7B61176',
            uniqueAnswer: false,
            computeSentimentScore: false,
            extractKeyPhrases: false,
            readOnly: false,
            dataClass: 0,
            charCounter: false,
            wordCounter: false,
            deleted: false,
            requiredValidationType: 0,
            enableSearchFilter: false,
            enableSelectAll: false,
            excludeFromLink: false,
            hideUntilSelected: false,
        },
    ],
    answerTypes: [
        {
            answerType: {
                openProperties: false,
                readOnly: false,
                id: '3A77D792-008A-463B-926F-663C9C115938',
                typeId: 'AnswerSelectionItem',
                builtIn: true,
                description: 'SelectionTextType',
                fieldWidth: -1,
                fieldHeight: 0,
                typeMode: 1,
                publicFieldResults: false,
                versioned: false,
                privateType: false,
                typeCSS: 'ngs-question__answer-selection',
            },
        },
        {
            answerType: {
                openProperties: false,
                readOnly: false,
                id: '7A06967B-8BC7-4F9A-826C-206DE9DF5320',
                typeId: 'AnswerFieldItem',
                builtIn: true,
                description: 'FieldLargeType',
                fieldWidth: -1,
                fieldHeight: 10,
                typeMode: 141522,
                publicFieldResults: false,
                versioned: false,
                privateType: false,
                typeCSS: 'ngs-question__answer-input ngs-question__answer-input-large',
            },
        },
        {
            answerType: {
                openProperties: false,
                readOnly: false,
                id: 'D54B1F97-E260-4E7C-92AB-3245F8194175',
                typeId: 'AnswerFieldItem',
                builtIn: true,
                description: 'FieldBasicType',
                fieldWidth: -1,
                fieldHeight: 1,
                typeMode: 141522,
                publicFieldResults: false,
                versioned: false,
                privateType: false,
                typeCSS: 'ngs-question__answer-input',
            },
        },
    ],
    multiLanguageTexts: [
        {
            multiLanguageTextUId: '28869B6F7C424905BBB50E3F2B3F0D88',
            languageItemId: 'C5AEB165F3564264ABD94159CE5530C4',
            languageCode: 'en-US',
            languageMessageTypeId: 1,
            itemText: 'Ease of access',
        },
        {
            multiLanguageTextUId: '64335C37B74544A386B46843525897B3',
            languageItemId: '66E6156705C548E283AE820C99027FAF',
            languageCode: 'en-US',
            languageMessageTypeId: 1,
            itemText: 'Accurate information',
        },
        {
            multiLanguageTextUId: 'B0FEC8C0DDC64BA9A82253DC2384D8A5',
            languageItemId: '6C34CDBE7B0A4CD0887C8EC8974CB96D',
            languageCode: 'en-US',
            languageMessageTypeId: 1,
            itemText: 'Consistent content',
        },
        {
            multiLanguageTextUId: 'CF9F76F862724A5F9436F0C5EA7EC65D',
            languageItemId: '82D4349CBCB94CAF83E0F249D5664DE3',
            languageCode: 'en-US',
            languageMessageTypeId: 1,
            itemText: 'Other',
        },
        {
            multiLanguageTextUId: '2749E1BB1D2342159A40677458A29800',
            languageItemId: '27ACB083CAD349D4B93505DFB35630AF',
            languageCode: 'en-US',
            languageMessageTypeId: 1,
            itemText: 'Difficult to access',
        },
        {
            multiLanguageTextUId: '6B0FDF3D0BAF4B459A6AE6AAB8CB1BFA',
            languageItemId: 'E59B0572787C4C32836355C53B1B6A38',
            languageCode: 'en-US',
            languageMessageTypeId: 1,
            itemText: 'Inaccurate information',
        },
        {
            multiLanguageTextUId: 'D97602A542634373839AC115E1B61EFD',
            languageItemId: '195F3674A8D440E7B49EA8A76D4FDBDF',
            languageCode: 'en-US',
            languageMessageTypeId: 1,
            itemText: 'Inconsistent content',
        },
        {
            multiLanguageTextUId: 'E626BD9EE9F14CBDB77A243B41B5F832',
            languageItemId: 'EBA70008C64B4E2EB04476C0EF65D61B',
            languageCode: 'en-US',
            languageMessageTypeId: 1,
            itemText: 'Other',
        },
        {
            multiLanguageTextUId: '2575F1A08AB4472086D92CD4ACB47143',
            languageItemId: 'OLcm__sfNaCP2yQ_gG1a',
            languageCode: 'en-US',
            languageMessageTypeId: 1,
            itemText: 'Prefer not to say',
        },
        {
            multiLanguageTextUId: 'A202E54E65DF462C9CB869C27B045CDD',
            languageItemId: 'OLcmgXANqae1twOtXhGa',
            languageCode: 'en-US',
            languageMessageTypeId: 1,
            itemText: 'Male',
        },
        {
            multiLanguageTextUId: '8171DC6BAAA24FBCBA022EA2944B37C6',
            languageItemId: 'OLcmhmcC1Vnq0V3ozwza',
            languageCode: 'en-US',
            languageMessageTypeId: 1,
            itemText: 'Female',
        },
        {
            multiLanguageTextUId: '994930B6D34C42B28EC6C9AE82C89DE7',
            languageItemId: 'O9dS8wLNWmhOa4ox0RYa',
            languageCode: 'en-US',
            languageMessageTypeId: 3,
            itemText: '<p>Was the content helpful?</p>\n',
        },
        {
            multiLanguageTextUId: 'A4F3149E64154FA2BF52642E7AC6C97C',
            languageItemId: 'OBPhaYxAXssimeva1X7a',
            languageCode: 'en-US',
            languageMessageTypeId: 3,
            itemText: '<p>version</p>\n',
        },
        {
            multiLanguageTextUId: '980A753C160F49EE837CBFE2F2854F1A',
            languageItemId: 'OBPhpQGM9Lef1Blo86da',
            languageCode: 'en-US',
            languageMessageTypeId: 3,
            itemText: '<p>environment</p>\n',
        },
        {
            multiLanguageTextUId: 'F3441C57E85347A9B30D2652CFB1715A',
            languageItemId: 'OFRZZx9ds475lN5SOSaa',
            languageCode: 'en-US',
            languageMessageTypeId: 3,
            itemText: '<p>Rating reasons</p>\n',
        },
        {
            multiLanguageTextUId: '1216A47EAB1B4364BC701BDFDA78B7C9',
            languageItemId: 'OFRZ_djnb7Autansgo0a',
            languageCode: 'en-US',
            languageMessageTypeId: 3,
            itemText: '<p>Note</p>\n',
        },
        {
            multiLanguageTextUId: '119B3BA1C360498884D3A08A7DE9418F',
            languageItemId: 'OFRaw38jb6_z40sHAM_a',
            languageCode: 'en-US',
            languageMessageTypeId: 3,
            itemText: '<p>Rating reasons</p>\n',
        },
        {
            multiLanguageTextUId: '2FD78B0BE2254317AF9B7069CF032BA2',
            languageItemId: 'OFRbewX_Dd4Dt9xTip_a',
            languageCode: 'en-US',
            languageMessageTypeId: 3,
            itemText: '<p>Note</p>\n',
        },
        {
            multiLanguageTextUId: '1C7869F20B3248CE8229D26DB4B99623',
            languageItemId: 'OLcm__sfNaCP2yQ_gG0a',
            languageCode: 'en-US',
            languageMessageTypeId: 3,
            itemText: '<p>Gender</p>\n',
        },
    ],
    skipQuestionConditions: [
        {
            skipQuestionCondition: {
                surveyId: 'O9dS6FIacFilIPje6bAa',
                id: 'B34CAA1739E9460A8C090B09402ADE83',
                conditionGroupId: '9FCBC20551924E94A44F535DDDCAC5C5',
                skipQuestionId: 'OFRZ_djnb7Autansgo0a',
                skipDisplayModeId: 2,
                conditionOrder: 1,
            },
            conditionGroup: {
                id: '9FCBC20551924E94A44F535DDDCAC5C5',
                surveyId: 'O9dS6FIacFilIPje6bAa',
                logicalOperator: 0,
            },
            conditionRules: [
                {
                    id: 'EE070E28D438403B82A81E1FBF4701D3',
                    conditionGroupId: '9FCBC20551924E94A44F535DDDCAC5C5',
                    questionId: 'O9dS8wLNWmhOa4ox0RYa',
                    answerId: 'O9dS8wLNWmhOa4ox0RZa',
                    conditionRuleTypeId: 1,
                    conditionalOperator: 1,
                    groupConditionalOperator: 1,
                    expressionDataTypeId: 1,
                },
            ],
        },
        {
            skipQuestionCondition: {
                surveyId: 'O9dS6FIacFilIPje6bAa',
                id: '331DB4ACEA904B1B88EB97A4EC2D1CAB',
                conditionGroupId: '4006A6294F7B431294C42276CB0B9B20',
                skipQuestionId: 'OFRZZx9ds475lN5SOSaa',
                skipDisplayModeId: 2,
                conditionOrder: 1,
            },
            conditionGroup: {
                id: '4006A6294F7B431294C42276CB0B9B20',
                surveyId: 'O9dS6FIacFilIPje6bAa',
                logicalOperator: 0,
            },
            conditionRules: [
                {
                    id: '8BBB41F0E5A34497ADE8B1C8CA1D482C',
                    conditionGroupId: '4006A6294F7B431294C42276CB0B9B20',
                    questionId: 'O9dS8wLNWmhOa4ox0RYa',
                    answerId: 'O9dS8wLNWmhOa4ox0RZa',
                    conditionRuleTypeId: 1,
                    conditionalOperator: 1,
                    groupConditionalOperator: 1,
                    expressionDataTypeId: 1,
                },
            ],
        },
        {
            skipQuestionCondition: {
                surveyId: 'O9dS6FIacFilIPje6bAa',
                id: 'EC0AF78F52DC485FB8FC8635C5074B9B',
                conditionGroupId: 'B03FA3AA473E4BE59E4F6339737222D8',
                skipQuestionId: 'OFRbewX_Dd4Dt9xTip_a',
                skipDisplayModeId: 2,
                conditionOrder: 1,
            },
            conditionGroup: {
                id: 'B03FA3AA473E4BE59E4F6339737222D8',
                surveyId: 'O9dS6FIacFilIPje6bAa',
                logicalOperator: 0,
            },
            conditionRules: [
                {
                    id: 'BC95770F671840F5B6C7A863CD646ADB',
                    conditionGroupId: 'B03FA3AA473E4BE59E4F6339737222D8',
                    questionId: 'O9dS8wLNWmhOa4ox0RYa',
                    answerId: 'O9dS8wLNWmhOa4ox0R_a',
                    conditionRuleTypeId: 1,
                    conditionalOperator: 1,
                    groupConditionalOperator: 1,
                    expressionDataTypeId: 1,
                },
            ],
        },
        {
            skipQuestionCondition: {
                surveyId: 'O9dS6FIacFilIPje6bAa',
                id: '88F0A628DCA3432CBEF5FF8B345D30B1',
                conditionGroupId: '3240B72FCDB84FDC8B293C8203E1D6AB',
                skipQuestionId: 'OFRaw38jb6_z40sHAM_a',
                skipDisplayModeId: 2,
                conditionOrder: 1,
            },
            conditionGroup: {
                id: '3240B72FCDB84FDC8B293C8203E1D6AB',
                surveyId: 'O9dS6FIacFilIPje6bAa',
                logicalOperator: 0,
            },
            conditionRules: [
                {
                    id: '5D9A636EBDE943B9A13C7C051C51D6F2',
                    conditionGroupId: '3240B72FCDB84FDC8B293C8203E1D6AB',
                    questionId: 'O9dS8wLNWmhOa4ox0RYa',
                    answerId: 'O9dS8wLNWmhOa4ox0R_a',
                    conditionRuleTypeId: 1,
                    conditionalOperator: 1,
                    groupConditionalOperator: 1,
                    expressionDataTypeId: 1,
                },
            ],
        },
        {
            skipQuestionCondition: {
                surveyId: 'O9dS6FIacFilIPje6bAa',
                id: 'FC7DECDF93464E0A9C9BECC918EFBAA7',
                conditionGroupId: '8FF429F7EEFD400287969BA86BB63F5E',
                skipQuestionId: 'OLcm__sfNaCP2yQ_gG0a',
                skipDisplayModeId: 2,
                conditionOrder: 1,
            },
            conditionGroup: {
                id: '8FF429F7EEFD400287969BA86BB63F5E',
                surveyId: 'O9dS6FIacFilIPje6bAa',
                logicalOperator: 0,
            },
            conditionRules: [
                {
                    id: '4AC0B23AEA2646A9BBDBB64A32D6E492',
                    conditionGroupId: '8FF429F7EEFD400287969BA86BB63F5E',
                    questionId: 'O9dS8wLNWmhOa4ox0RYa',
                    answerId: 'O9dS8wLNWmhOa4ox0R_a',
                    conditionRuleTypeId: 1,
                    conditionalOperator: 1,
                    groupConditionalOperator: 2,
                    expressionDataTypeId: 1,
                },
                {
                    id: 'OLht3AZnZY0cKjlWKZAa',
                    conditionGroupId: '8FF429F7EEFD400287969BA86BB63F5E',
                    questionId: 'O9dS8wLNWmhOa4ox0RYa',
                    answerId: 'O9dS8wLNWmhOa4ox0RZa',
                    conditionRuleTypeId: 1,
                    conditionalOperator: 1,
                    groupConditionalOperator: 1,
                    expressionDataTypeId: 1,
                },
            ],
        },
    ],
    formStyles: [
        {
            readOnly: true,
            id: 'Mz5HiBsMY7bLES03XQwa',
            formStyleTypeId: 1,
            name: 'MOE',
            publicStyle: true,
            builtIn: true,
            darkMode: false,
            surveyAlignId: 1,
            pageHeader:
                '<div class="header">\n<div class="header-content">\n<h2>&nbsp;<img src="ngsurveymedia.ashx?gid=NkyRt7AkIeXg9lBOKYBa" style="max-width:100%;max-height:100%" /></h2>\n\n<p>تفاصيل الإستبيان</p>\n</div>\n<script>\nwindow.setHeader=function(){\n\nvar docTitle = document.getElementsByClassName("surTitle");\ntry{\ndocTitle[0].innerText=document.querySelector(\'#surveyTitle\').innerHTML;\ndocTitle[1].innerText=document.querySelector(\'#surveyTitle\').innerHTML;\n}catch(e){}\n}\ndocument.addEventListener("load", window.setHeader);\nwindow.setHeader();\n};\n</script></div>\n',
            pageFooter:
                '<div class="footer-content">\n<hr />\n<h3><img alt="logo" src="/ngsurveymedia.ashx?gid=Mr1xpUHo_8NGJ38Sptea" />&nbsp;&nbsp; جميع الحقوق محفوظة لبصر &copy;2021</h3>\n</div>\n',
            cSSCode:
                ".ngs-survey__page {\n  background-color: var(--ngs-formbackground-color);\n  box-shadow: 0px 0px 0px 0px #000000;\n  color: var(--ngs-text-color);\n  border-radius: 4px;\n}\n\n.ngs-survey__page-header {\n  padding: 20px 40px 20px 40px;\n}\n\n.ngs-question {\n  background-color: #fff;\n  padding: 30px 30px 30px 30px;\n  margin: 0px 0px 20px 0px;\n  border: 0px;\n  border-radius: 8px;\n  box-shadow: 0 1px 2px 0 rgba(18,78,109, 0.3), 0 1px 3px 1px rgba(18,78,109, 0.15);\n}\n\n.ngs-survey__thanks-page {\n  background-color: #fff;\n  padding: 30px 30px 30px 30px;\n  margin: 0px 0px 13px 0px;\n  border: 0px;\n  border-radius: 8px;\n  box-shadow: 0 1px 2px 0 rgba(18,78,109, 0.3), 0 1px 3px 1px rgba(18,78,109, 0.15);\n  background: linear-gradient(20deg,rgba(209,219,228,.1) 0%,#fff 80%,rgba(209,219,228,.1) 100%);\n}\n\n.ngs-survey__page-footer-actions-container {\n  padding: 8px 0px 0px;\n}\n\n.ngs-question.ngs-question-static {\n  background-color: transparent;\n  padding: 0px 30px 30px 30px;\n  margin: 0px;\n  border: 0px;\n  border-radius: 0px;\n  box-shadow: none;\n  background: none;\n}\n\n.ngs-survey__header {\n  height: 0px;\n}\n\n.ngs-survey__wrapper {\n  padding: 10px 24px 0px 24px;\n}\n\n.ngs-survey__button {\n  padding: 4px 4px 4px 4px;\n  border-radius: 7px;\n  margin: 0px 0px 0px 0px;\n  background-color: var(--ngs-default-primary-color);\n  font-family: 'IBMPlexSansArabic', Arial, sans-serif;\n  font-weight: 500;\n  font-size: 14px;\n  border: 0;\n  color: var(--ngs-text-primary-color);\n}\n\nbody {\n  font-family: 'IBMPlexSansArabic', Arial, sans-serif;\n}\n\n.ngs-survey__page-footer {\n  padding: 0px 0px 10px 0px;\n}\n\n@font-face {\n  font-family:'IBMPlexSansArabic';src:url('/ngsurveymedia.ashx?gid=MrLpi8yKCwMRRNm6DLUa') format('woff'),  font-weight;font-style:normal;font-display:block;\n}\n\n.ngs-survey {\n  font-family: 'IBMPlexSansArabic', Arial, sans-serif;\n  width: 100%;\n}\n\n.header {\n  background: linear-gradient(246.07deg, #4BDBC1 -12.27%, #358A7B 99.52%);\n  min-height: 100px;\n  display: flex;\n  justify-content: center;\n  flex-direction: column;\n  color: #fff;\n}\n\n.header h2 {\n  margin: 0;\n}\n\n.header-content,.footer-content {\n  max-width: 1000px;\n  width: 100%;\n  padding: 0 24px 0 24px;\n  margin: auto;\n}\n\n.header p {\n  padding: 10px 0 0;\n}\n\n.ngs-survey__flow-banner {\n  height: 0px;\n}\n\nhr {\n  border: none;\n  border-bottom: solid 2px #19AF94;\n}\n\n@media screen and (max-width:599px) {\n  .ngs-survey__header {\n    height: 0px;\n  }\n\n  .ngs-survey__wrapper {\n    padding: 10px 24px 0px 24px;\n  }\n}\n\n@media screen and (min-width:600px) {\n  .ngs-survey__header {\n    height: 0px;\n  }\n}\n.ngs-survey__progress-bar-percentage { \n    text-shadow: 0px 1px 5px black;\n    color: #fff;\n}",
            cSSTheme:
                '--ngs-font:IBMPlexSansArabic;\n ;\n --ngs-background-color: #f5f9fc;\n --ngs-formbackground-color:transparent;\n --ngs-text-color: #212121;\n --ngs-dark-primary-color:#0d7461;\n --ngs-default-primary-color:#19af94;\n --ngs-default-primary-transparent-color: rgba(49, 136, 201, .1);\n --ngs-light-primary-color: #c1dbef;\n --ngs-text-primary-color: #fff;\n --ngs-accent-color:#19af94;\n --ngs-dark-accent-color:#1abc9f;\n --ngs-light-accent-color:#34e6c5;\n --ngs-text-accent-color: #fff;\n --ngs-divider-color: #bdbdbd;\n --ngs-error-color: #ff5b59;\n --ngs-error-text-color: #fff;\n --ngs-light-error-color: #ffebee;\n --ngs-header-background-color:#02c8a4;\n ',
            fontURL: '/ngsurveymedia.ashx?gid=MrLpi8yKCwMRRNm6DLUa',
            fontFamilyName: 'IBMPlexSansArabic',
        },
    ],
    supportedLanguages: [
        {
            languageCode: 'ar-SA',
            description: 'ArabicLanguage',
            isReverseLanguage: true,
            defaultLanguage: true,
        },
        {
            languageCode: 'en-US',
            description: 'EnglishUSLanguage',
            isReverseLanguage: false,
            defaultLanguage: false,
        },
    ],
    lastModified: 638861909753145387n,
} as const
